# ldr-rs: LDraw models for Rust
# Copyright (C) 2017-2025  Edgar Gonzàlez i Pellicer
#
# This file is part of ldr-rs.
#
# ldr-rs is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[package]
name = "ldr-rs"
description = "Library to parse LDraw models in Rust"
authors = ["Edgar Gonzàlez Pellicer <edgar.gip@gmail.com>"]
version = "0.1.0"
license = "GPL-3.0-or-later"
homepage = "https://github.com/edgar-gip/ldr-rs"
repository = "https://github.com/edgar-gip/ldr-rs"
edition = "2018"
keywords = ["ldraw", "lego"]
categories = ["parser-implementations", "rendering::data-formats"]

[dependencies]
lazy_static = "^1.5"
nalgebra = "^0.30"
phf = { version = "^0.13", features = ["macros"] }
regex = "^1.12"

[dev-dependencies]
kiss3d = "<0.37"

# Local Variables:
# coding: utf-8
# End:
